version: '3.4'

networks:
  reverseproxy:
    driver: bridge


services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    networks:
      - reverseproxy
    volumes:
      #docker-compose.yml과 같은 레벨에 둔 nginx.conf를 mount.
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - khumon

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  khumon:
    container_name: khumon
    image: chy0310/khumon
    expose:
      - 8000
    networks:
      - reverseproxy
    depends_on:
      - redis





  # ports는 외부 컨테이너에서 80 포트로 진입 시 80 포트로 넘겨준다는 뜻이며,
  #expose는 같은 호스트 안에 있는 내부 컨테이너에서만 8080 포트로 진입할 수 있다는 뜻이다.
