spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  data:
    redis:
      host: ${REDIS_HOST} #localhost
      port: ${REDIS_PORT} #6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: ${GOOGLE_CLIENT_SCOPE}

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: ${NAVER_AUTHORIZATION_GRANT_TYPE}
            scope: ${NAVER_SCOPE}
            client-name: Naver

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: ${KAKAO_CLIENT_AUTHENTICATION_METHOD}
            authorization-grant-type: ${KAKAO_AUTHORIZATION_GRANT_CODE}
            scope: ${KAKAO_SCOPE}
            client-name: Kakao

        provider:
          naver:
            authorization_uri: ${NAVER_AUTHORIZATION_URI}
            token_uri: ${NAVER_TOKEN_URI}
            user-info-uri: ${NAVER_USER_INFO_URI}
            user_name_attribute: ${NAVER_USER_NAME_ATTRIBUTE}

          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: ${KAKAO_USER_NAME_ATTRIBUTE}


  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 500MB


jwt:
  secret : ${JWT_SECRET}
  access:
    expiration:  ${JWT_EXPIRATION}
    header:  ${JWT_HEADER}




server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json, application/zip, application/octet-stream, application/pdf, video/mp4
